version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" # host:image
    volumes: # get the updates made in the project into the docker image in real time
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
